# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - id: resource-rbd-debug
    binary: resource-rbd.dbg
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/yuyang0/resource-rbd/version.REVISION={{.Commit}}
      - -X github.com/yuyang0/resource-rbd/version.VERSION={{.Env.VERSION}}
      - -X github.com/yuyang0/resource-rbd/version.BUILTAT={{.Date}}
    hooks:
      post:
        - cp {{.Path}} ./resource-rbd-{{.Os}}.dbg
    goos:
      - darwin
      - linux
    goarch:
      - amd64

  # the best practice is using prebuilt builder
  # however it's a Pro feature
  - id: resource-rbd-linux
    binary: resource-rbd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
      - -X github.com/yuyang0/resource-rbd/version.REVISION={{.Commit}}
      - -X github.com/yuyang0/resource-rbd/version.VERSION={{.Env.VERSION}}
      - -X github.com/yuyang0/resource-rbd/version.BUILTAT={{.Date}}
    hooks:
      post:
        - cp ./resource-rbd-{{.Os}}.dbg {{.Path}}
        - strip {{.Path}}
    goos:
      - linux
    goarch:
      - amd64

  - id: resource-rbd-darwin
    binary: resource-rbd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s
      - -X github.com/yuyang0/resource-rbd/version.REVISION={{.Commit}}
      - -X github.com/yuyang0/resource-rbd/version.VERSION={{.Env.VERSION}}
      - -X github.com/yuyang0/resource-rbd/version.BUILTAT={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
